# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches-ignore: 
      - '**-alpha'
      - '**-tmp'
      - '**-temp'
  pull_request:
    branches-ignore: 
      - '**-alpha'
      - '**-tmp'
      - '**-temp'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Clean and Package
      run: mvn clean package
    - name: Show jacoco.xml
      run: cat servicekeeper-core/target/site/jacoco/jacoco.xml
